SELECT YEAR(A.DIFFERENTIATION_DATE) YEAR, (B.MAX_COLONY - A.SIZE_OF_COLONY) YEAR_DEV, A.ID
FROM ECOLI_DATA A
LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_COLONY
            FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;