SELECT fn.ID, fni.FISH_NAME, fn.LENGTH
FROM FISH_INFO fn 
INNER JOIN FISH_NAME_INFO fni
ON fn.FISH_TYPE = fni.FISH_TYPE
WHERE fn.FISH_TYPE
IN (SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH))
ORDER BY ID;